### PR TITLE
Synchronous Python Playground.

### PR DESCRIPTION
**Pull request by Nibba2018**
It solves this [issue](https://github.com/appwrite/appwrite/issues/503) to create a Playground for Python SDK.
The following API calls are mentioned:
### API Calls
* [X] Create Collection
* [X] List Collection
* [X] Add Document
* [X] List Document
* [X] Upload File
* [X] Create User
* [X] List User

### CODE REVIEW

**Comment by eldadfux** [comment]
@Nibba2018 looks great so far, a few things:
1. Did you manage to solve the issue with async calls?
2. Please add a readme file similar to the one we have in the node.js playground

**Comment by eldadfux** [comment]
Just figured the README is in another PR 👍🏻

**Comment by Nibba2018** [comment]
Hi @eldadfux , Thank you for appreciating my work.

In order to solve issues with the async call, the python sdk classes of `appwrite` needs to implement `__await__()` magic method to make it `awaitable` and hence asynchronous.

**Comment by eldadfux** [comment]
Hey @Nibba2018 any chance you could open a relevant issue about this on https://github.com/appwrite/sdk-generator? (maybe even suggest a PR?)

**Comment by Nibba2018** [comment]
@eldadfux Sure would love to do that.

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

**Pull request merged**
