### PR TITLE
feat-34-use-commad-line -arguments-for-create_user()-function

### PR DESCRIPTION
**Pull request by AugustinJose1221**
Changed the function description of run_all_tasks() and added three new arguments. The email, password and name can now be passed as inputs to the function through the command line.

### CODE REVIEW

**Comment by Nibba2018** [comment]
@AugustinJose1221  Make the feature of adding creds through command-line optional instead of completely removing it.

**Comment by AugustinJose1221** [comment]
Right on it

**Comment by AugustinJose1221** [comment]
Changes made 👍

**Comment by eldadfux** [comment]
Hey @AugustinJose1221, we appreciate the PR, but the goal of this library is not to be usable, or sophisticated, just to use as a very very simple example and overview for new developers wanting to try the Appwrite SDK. I'm closing the PR, but adding the `hacktoberfest-accepted` label for your effort.

**Pull request closed without merging**
