### PR TITLE
Playground Updated

### PR DESCRIPTION
**Pull request by Shivansh-1616**

### CODE REVIEW

**Comment by Nibba2018** [comment]
`INVALID` PR

**Comment by Shivansh-1616** [comment]
> `INVALID` PR

It's a playground in which I am trying to build things

**Comment by vamsi963601** [comment]
Bro, dont just do it for hactoberfest. If you really wanna contribute no offence but just read the focs og appwrite first and then you will understand how to contribute

**Comment by eldadfux** [comment]
We love contribution, but we suggest you try and submit more meaningful PRs by exploring any of our [open issues](https://github.com/appwrite/appwrite/issues). If you have any problem or need help, please join our Discord community: https://appwrite.io/discord and use the #maintainers channel.

**Pull request closed without merging**
