### PR TITLE
Asynchronous Python Playground

### PR DESCRIPTION
**Pull request by Nibba2018**
Hi @eldadfux , I tried a workaround to run python playground asynchronously. Do have a look.
This PR refers to this [issue](https://github.com/appwrite/appwrite/issues/503) 

### API Calls
* [X] Create Collection
* [X] List Collection
* [X] Add Document
* [X] List Document
* [X] Upload File
* [X] Create User
* [X] List User

### CODE REVIEW

**Comment by eldadfux** [comment]
@Nibba2018 do you think this PR will make a better default example than the synced version?

**Comment by Nibba2018** [comment]
@eldadfux , I did some tests and found that this takes the same amount of time to execute compared to the synced version. So I am still a bit doubtful whether this is truly asynchronous. I think we have to implement `__await__()` for sdk classes to get better results. I am currently creating a detailed issue on `sdk-generator`.

**Comment by Niraj-Kamdar** [comment]
This won't work because there isn't any awaitable coroutine in your asynchronous functions. This will just run synchronously and will take more time then synchronous counterpart due to the additional overhead of the event loop. You have two options to make it asynchronous either by running it in another thread by using [run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) or make the underlying library asynchronous. The first one is easy.

**Comment by Nibba2018** [comment]
@Niraj-Kamdar , Okay let me try this.

**Pull request closed without merging**
